version: '3.8'

services:
  # 백엔드 서비스 (Python FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # SSL 관련 환경 변수 추가
      - PYTHONHTTPSVERIFY=0
      - REQUESTS_CA_BUNDLE=""
      - CURL_CA_BUNDLE=""
    env_file:
      - .env
    # DNS 설정 (구글 DNS 사용)
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    volumes:
      - ./backend:/app
      - ./backend/results:/app/results
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 프론트엔드 서비스 (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend

networks:
  default:
    driver: bridge
